library verilog;
use verilog.vl_types.all;
entity requestor_arb_wire_path is
    port(
        clock           : in     vl_logic;
        reset           : in     vl_logic;
        r_req_dest      : in     vl_logic;
        state           : in     vl_logic_vector(2 downto 0);
        r_pte_reserved_for_hardware: in     vl_logic_vector(15 downto 0);
        resp_ppn        : in     vl_logic_vector(37 downto 0);
        r_pte_reserved_for_software: in     vl_logic_vector(1 downto 0);
        r_pte_d         : in     vl_logic;
        r_pte_a         : in     vl_logic;
        r_pte_g         : in     vl_logic;
        r_pte_u         : in     vl_logic;
        r_pte_x         : in     vl_logic;
        r_pte_w         : in     vl_logic;
        r_pte_r         : in     vl_logic;
        r_pte_v         : in     vl_logic;
        arb_io_in_0_ready: in     vl_logic;
        io_requestor_0_req_valid: in     vl_logic;
        io_requestor_0_req_bits_prv: in     vl_logic_vector(1 downto 0);
        io_requestor_0_req_bits_pum: in     vl_logic;
        io_requestor_0_req_bits_mxr: in     vl_logic;
        io_requestor_0_req_bits_addr: in     vl_logic_vector(26 downto 0);
        io_requestor_0_req_bits_store: in     vl_logic;
        io_requestor_0_req_bits_fetch: in     vl_logic;
        arb_io_in_1_ready: in     vl_logic;
        io_requestor_1_req_valid: in     vl_logic;
        io_requestor_1_req_bits_prv: in     vl_logic_vector(1 downto 0);
        io_requestor_1_req_bits_pum: in     vl_logic;
        io_requestor_1_req_bits_mxr: in     vl_logic;
        io_requestor_1_req_bits_addr: in     vl_logic_vector(26 downto 0);
        io_requestor_1_req_bits_store: in     vl_logic;
        io_requestor_1_req_bits_fetch: in     vl_logic;
        arb_clock       : out    vl_logic;
        arb_reset       : out    vl_logic;
        io_requestor_0_resp_valid: out    vl_logic;
        io_requestor_0_resp_bits_pte_reserved_for_hardware: out    vl_logic_vector(15 downto 0);
        io_requestor_0_resp_bits_pte_ppn: out    vl_logic_vector(37 downto 0);
        io_requestor_0_resp_bits_pte_reserved_for_software: out    vl_logic_vector(1 downto 0);
        io_requestor_0_resp_bits_pte_d: out    vl_logic;
        io_requestor_0_resp_bits_pte_a: out    vl_logic;
        io_requestor_0_resp_bits_pte_g: out    vl_logic;
        io_requestor_0_resp_bits_pte_u: out    vl_logic;
        io_requestor_0_resp_bits_pte_x: out    vl_logic;
        io_requestor_0_resp_bits_pte_w: out    vl_logic;
        io_requestor_0_resp_bits_pte_r: out    vl_logic;
        io_requestor_0_resp_bits_pte_v: out    vl_logic;
        io_requestor_1_resp_valid: out    vl_logic;
        io_requestor_1_resp_bits_pte_reserved_for_hardware: out    vl_logic_vector(15 downto 0);
        io_requestor_1_resp_bits_pte_ppn: out    vl_logic_vector(37 downto 0);
        io_requestor_1_resp_bits_pte_reserved_for_software: out    vl_logic_vector(1 downto 0);
        io_requestor_1_resp_bits_pte_d: out    vl_logic;
        io_requestor_1_resp_bits_pte_a: out    vl_logic;
        io_requestor_1_resp_bits_pte_g: out    vl_logic;
        io_requestor_1_resp_bits_pte_u: out    vl_logic;
        io_requestor_1_resp_bits_pte_x: out    vl_logic;
        io_requestor_1_resp_bits_pte_w: out    vl_logic;
        io_requestor_1_resp_bits_pte_r: out    vl_logic;
        io_requestor_1_resp_bits_pte_v: out    vl_logic;
        io_requestor_0_req_ready: out    vl_logic;
        arb_io_in_0_valid: out    vl_logic;
        arb_io_in_0_bits_prv: out    vl_logic_vector(1 downto 0);
        arb_io_in_0_bits_pum: out    vl_logic;
        arb_io_in_0_bits_mxr: out    vl_logic;
        arb_io_in_0_bits_addr: out    vl_logic_vector(26 downto 0);
        arb_io_in_0_bits_store: out    vl_logic;
        arb_io_in_0_bits_fetch: out    vl_logic;
        io_requestor_1_req_ready: out    vl_logic;
        arb_io_in_1_valid: out    vl_logic;
        arb_io_in_1_bits_prv: out    vl_logic_vector(1 downto 0);
        arb_io_in_1_bits_pum: out    vl_logic;
        arb_io_in_1_bits_mxr: out    vl_logic;
        arb_io_in_1_bits_addr: out    vl_logic_vector(26 downto 0);
        arb_io_in_1_bits_store: out    vl_logic;
        arb_io_in_1_bits_fetch: out    vl_logic
    );
end requestor_arb_wire_path;
